name: GitHub-CI


on: [push]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: payze.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ env.DEBUG }}
          SECRET_KEY: ${{ env.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}

          API_URL: ${{ env.API_URL }}
          API_KEY: ${{ env.API_KEY }}
          API_SECRET: ${{ env.API_SECRET }}
          CALL_BACK_URL: ${{ env.CALL_BACK_URL }}

        run: python3 manage.py test
